---
- name: Create local user accounts on Access Closet 1 devices
  hosts: linux, windows
  vars:
    windows_user_mapping:
      10.10.1.35: { name: "DesktopUser1", password: "Pssw0rd1!" }
      10.10.1.36: { name: "DesktopUser2", password: "Pssw0rd1!" }
      10.10.1.43: { name: "DesktopUser3", password: "Pssw0rd1!" }
      10.10.1.29: { name: "DesktopUser4", password: "Pssw0rd1!" }
    linux_user_mapping:
      10.10.1.56: { name: "TestUser1", password: "Pssw0rd1!" }
      10.10.1.57: { name: "TestUser2", password: "Pssw0rd1!" }

  tasks:

    - name: Add local user on Windows desktops
      ansible.windows.win_user:
        name: "{{ windows_user_mapping[inventory_hostname].name }}"
        password: "{{ windows_user_mapping[inventory_hostname].password }}"
        groups:
          - "Administrators"
        state: present
      when: "'windows' in group_names"
      tags: windows

    - name: Add local user on Ubuntu test boxes
      become: yes
      vars:
        ansible_sudo_pass: P@ssw0rd
      ansible.builtin.user:
        name: "{{ linux_user_mapping[inventory_hostname].name }}"
        password: "{{ linux_user_mapping[inventory_hostname].password | password_hash('sha512') }}"
        shell: /bin/bash
        groups: sudo
        state: present
      when: "'linux' in group_names"
      tags: ubuntu

- name: Create local user accounts on switches
  hosts: exos
  gather_facts: no
  tasks:
    - name: Create user
      exos_config:
        lines:
          - create account admin "Local-Admin" Pssw0rd1!
      register: result
    
    - name: Verify creation
      debug:
        var: result

