linux:
  hosts:
    10.10.1.56:
    10.10.1.57:
  vars:
    ansible_password: P@ssw0rd
windows:
  hosts:  
    10.10.1.35:
    10.10.1.36:
    10.10.1.43:
    10.10.1.29:
    10.10.1.28:
  vars:
    ansible_port: 5985
    ansible_user: Administrator
    ansible_password: P@ssw0rd
    ansible_connection: winrm
exos:
  hosts:
    10.10.1.30:
    10.10.1.31:
    10.10.1.32:
    10.10.1.22:
  vars:
    ansible_user: admin
    ansible_password: ""
    ansible_connection: network_cli
    ansible_network_os: exos
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: password
    ansible_command_timeout: 60
